global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8082']
  
  - job_name: 'ml-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ml-service:8000']
